[package]
name = "bevy_typed_gltf"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_asset = "0.14.0"
bevy_gltf = "0.14.0"
bevy_scene = "0.14.0"
bevy_typed_gltf_macros = { path = "macros", version = "0.1.0" }
