[package]
name = "bevy_typed_gltf_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.72", features = ["full", "parsing", "extra-traits"] }
quote = "1.0"
